name = "ASAP7PDK"
uuid = "5f726cbb-fb92-4cd0-9fae-dbb64c46e42b"
version = "0.2.1"
#path = "cedar/ASAP7PDK.jl"

[deps]
CMC = "db13d295-e716-48aa-bdca-f6cce3d4ecc6"
CedarSim = "9075980a-f0c7-46d2-945a-cc5bead5ad4a"
