name = "ASAP7PDK"
uuid = "68451d9d-dee8-4953-9213-4e693cae3dc0"
authors = ["Pepijn de Vos <pepijn.devos@juliahub.com>"]
version = "0.1.0"

[deps]
CMC = "db13d295-e716-48aa-bdca-f6cce3d4ecc6"
CedarSim = "9075980a-f0c7-46d2-945a-cc5bead5ad4a"
